export const imageData = {
  Черный: 'images/colors/1.webp',
  Черный1: 'images/colors/2.webp',
  Черный2: 'images/colors/3.webp',
  Черный3: 'images/colors/4.webp',
  Черный4: 'images/colors/5.webp',
  Черный5: 'images/colors/6.webp',
  Серый: 'images/colors/7.webp',
  Серый1: 'images/colors/8.webp',
  Серый2: 'images/colors/9.webp',
  Серый3: 'images/colors/10.webp',
  'Светло-зеленый': 'images/colors/11.webp',
  'Светло-зеленый1': 'images/colors/12.webp',
  'Светло-зеленый2': 'images/colors/13.webp',
};
